const std = @import("std");
const config = @import("../config.zig");

// Emits Whisper GBNF and a Vosk phrase-list JSON (not JSGF; [unk] added) from one commands.json.

pub const OutputPaths = struct {
    gbnf: []const u8,
    vosk_json: []const u8,
};

pub const default_output = OutputPaths{
    .gbnf = "generated/commands.gbnf",
    .vosk_json = "generated/commands.vosk.json",
};

pub const UserOverrides = struct {
    gbnf: []const u8 = "config/commands.gbnf.user",
    vosk_json: []const u8 = "config/commands.vosk.json.user",
};

pub const GrammarKind = enum { gbnf, vosk_json };

pub const ResolvedGrammar = struct {
    kind: GrammarKind,
    path: []const u8,
    from_user_override: bool,
};

pub fn writeAll(allocator: std.mem.Allocator, set: *const config.CommandSet, out: OutputPaths) !void {
    try ensureParentDir(out.gbnf);
    try ensureParentDir(out.vosk_json);

    {
        var f = try std.fs.cwd().createFile(out.gbnf, .{ .truncate = true });
        defer f.close();
        try writeGbnf(f.writer(), set.commands);
    }
    {
        var f = try std.fs.cwd().createFile(out.vosk_json, .{ .truncate = true });
        defer f.close();
        try writeVoskJson(f.writer(), set.commands);
    }
    _ = allocator;
}

pub fn writeGbnf(writer: anytype, commands: []const config.Command) !void {
    try writer.writeAll("# Auto-generated by Deckhand — DO NOT EDIT.\n");
    try writer.writeAll("# To customise, copy to config/commands.gbnf.user (used verbatim when newer).\n\n");
    try writer.writeAll("root ::= command\n");
    try writer.writeAll("command ::= ");

    var first = true;
    for (commands) |cmd| {
        for (cmd.phrases) |phrase| {
            if (!first) try writer.writeAll(" | ");
            first = false;
            try writer.writeByte('"');
            try writeGbnfEscaped(writer, phrase);
            try writer.writeByte('"');
        }
    }
    try writer.writeByte('\n');
}

pub fn writeVoskJson(writer: anytype, commands: []const config.Command) !void {
    try writer.writeByte('[');
    var first = true;
    for (commands) |cmd| {
        for (cmd.phrases) |phrase| {
            if (!first) try writer.writeAll(", ");
            first = false;
            try writer.writeByte('"');
            try writeJsonStringBody(writer, normalisePhrase(phrase));
            try writer.writeByte('"');
        }
    }
    // Explicit unknown slot so out-of-vocab utterances don't force a spurious match.
    if (!first) try writer.writeAll(", ");
    try writer.writeAll("\"[unk]\"]");
}

fn writeGbnfEscaped(writer: anytype, s: []const u8) !void {
    for (s) |c| switch (c) {
        '"' => try writer.writeAll("\\\""),
        '\\' => try writer.writeAll("\\\\"),
        else => try writer.writeByte(c),
    };
}

fn writeJsonStringBody(writer: anytype, s: []const u8) !void {
    for (s) |c| switch (c) {
        '"' => try writer.writeAll("\\\""),
        '\\' => try writer.writeAll("\\\\"),
        '\n' => try writer.writeAll("\\n"),
        '\r' => try writer.writeAll("\\r"),
        '\t' => try writer.writeAll("\\t"),
        0x00...0x08, 0x0B, 0x0C, 0x0E...0x1F => try writer.print("\\u{x:0>4}", .{c}),
        else => try writer.writeByte(c),
    };
}

// Placeholder for Vosk phrase normalisation (lowercase, collapse spaces, strip punctuation).
fn normalisePhrase(s: []const u8) []const u8 {
    // Returned as-is to keep codegen allocation-free; normalise when editing commands.json.
    return s;
}

fn ensureParentDir(path: []const u8) !void {
    if (std.fs.path.dirname(path)) |dir| {
        std.fs.cwd().makePath(dir) catch |err| switch (err) {
            error.PathAlreadyExists => {},
            else => return err,
        };
    }
}

pub fn resolveGrammarPath(
    kind: GrammarKind,
    source_commands_path: []const u8,
    overrides: UserOverrides,
    generated: OutputPaths,
) ResolvedGrammar {
    const user_path = switch (kind) {
        .gbnf => overrides.gbnf,
        .vosk_json => overrides.vosk_json,
    };
    const gen_path = switch (kind) {
        .gbnf => generated.gbnf,
        .vosk_json => generated.vosk_json,
    };

    const src_mtime = statMtime(source_commands_path) orelse 0;
    const user_mtime = statMtime(user_path) orelse {
        return .{ .kind = kind, .path = gen_path, .from_user_override = false };
    };

    if (user_mtime >= src_mtime) {
        return .{ .kind = kind, .path = user_path, .from_user_override = true };
    }
    return .{ .kind = kind, .path = gen_path, .from_user_override = false };
}

fn statMtime(path: []const u8) ?i128 {
    const stat = std.fs.cwd().statFile(path) catch return null;
    return stat.mtime;
}

// ---- tests ----

test "gbnf output contains all phrases quoted" {
    const src =
        \\{ "version": 1, "commands": [
        \\  { "id":"a","phrases":["landing gear","gear"],"action":{"type":"tap","keys":"n"} },
        \\  { "id":"b","phrases":["fire"],"action":{"type":"mouse","button":"left","kind":"click"} }
        \\]}
    ;
    var set = try config.loadFromSlice(std.testing.allocator, src);
    defer set.deinit();

    var buf: std.ArrayList(u8) = .init(std.testing.allocator);
    defer buf.deinit();
    try writeGbnf(buf.writer(), set.commands);

    const out = buf.items;
    try std.testing.expect(std.mem.indexOf(u8, out, "\"landing gear\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "\"gear\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "\"fire\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "root ::= command") != null);
}

test "vosk json is a valid JSON array with [unk]" {
    const src =
        \\{ "version": 1, "commands": [
        \\  { "id":"a","phrases":["landing gear","gear"],"action":{"type":"tap","keys":"n"} }
        \\]}
    ;
    var set = try config.loadFromSlice(std.testing.allocator, src);
    defer set.deinit();

    var buf: std.ArrayList(u8) = .init(std.testing.allocator);
    defer buf.deinit();
    try writeVoskJson(buf.writer(), set.commands);

    const out = buf.items;
    try std.testing.expect(std.mem.startsWith(u8, out, "["));
    try std.testing.expect(std.mem.endsWith(u8, out, "]"));
    try std.testing.expect(std.mem.indexOf(u8, out, "\"[unk]\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "\"landing gear\"") != null);

    // Round-trip parse to confirm valid JSON.
    var parsed = try std.json.parseFromSlice(std.json.Value, std.testing.allocator, out, .{});
    defer parsed.deinit();
    try std.testing.expect(parsed.value == .array);
}

test "gbnf escapes embedded quotes" {
    const src =
        \\{ "version": 1, "commands": [
        \\  { "id":"a","phrases":["say \"hi\""],"action":{"type":"tap","keys":"a"} }
        \\]}
    ;
    var set = try config.loadFromSlice(std.testing.allocator, src);
    defer set.deinit();

    var buf: std.ArrayList(u8) = .init(std.testing.allocator);
    defer buf.deinit();
    try writeGbnf(buf.writer(), set.commands);
    try std.testing.expect(std.mem.indexOf(u8, buf.items, "\\\"") != null);
}

test "vosk grammar uses only enabled phrases" {
    const src =
        \\{ "version": 2, "commands": [
        \\  { "id":"a","phrases":["landing gear"],"disabled_phrases":["gear up"],"action":{"type":"tap","keys":"n"} },
        \\  { "id":"b","phrases":[],"disabled_phrases":["boost"],"action":{"type":"tap","keys":"b"} }
        \\]}
    ;
    var set = try config.loadFromSlice(std.testing.allocator, src);
    defer set.deinit();
    var buf: std.ArrayList(u8) = .init(std.testing.allocator);
    defer buf.deinit();
    try writeVoskJson(buf.writer(), set.commands);
    try std.testing.expectEqualStrings("[\"landing gear\", \"[unk]\"]", buf.items);
}
